### PR TITLE
[branch/5.15-21.08] pyqt: Enable more features

### PR DESCRIPTION
**Pull request by tinywrkb**
Enable more PyQt features: tools, docstrings, QML and Designer plugins. See commit messages for more details.
Update cleanup script and change WebEngine removal environment variable (backward compat).

### CODE REVIEW

**Comment by ramcq** [comment]
Something missing?
```
pyrcc5 qt/dg.qrc > qt/dg_rc.py
/usr/bin/python: No module named PyQt5.pyrcc_main
```

**Comment by tinywrkb** [comment]
> Something missing?
> 
> ```
> pyrcc5 qt/dg.qrc > qt/dg_rc.py
> /usr/bin/python: No module named PyQt5.pyrcc_main
> ```

Yes, and also pylupdate. I'll send an update soon.

**Comment by tinywrkb** [comment]
I need to make a few more adjustments for the cleanup script, so it will be merged a bit later.

**Comment by JakobDev** [comment]
How should the Designer Plugin be used from the BaseApp?

**Comment by tinywrkb** [comment]
> How should the Designer Plugin be used from the BaseApp?

That's a good question. I haven't tried it, or given any thought, and it might been simpler or could be automated (the usual `enable.sh`) if this was an SDK extension.  

I suspect that you can make it work if:  
1. You have the SDK installed
2. Run Qt Designer from the SDK with the base application mounted. The usual `flatpak run --devel --command=/usr/bin/designer FLATPAK_ID` should work, though you'll need to add proper permissions or create overrides.
3. You include the full path to plugin dir from the base application in `QT_PLUGIN_PATH` (e.g. `/app/lib/plugins` for `5.15.-21.08`). To avoid breaking Qt Designer, you might need to append the path of the runtime's plugins dir(e.g. `/usr/lib/plugins`), with the usual colons separator.

**Comment by tinywrkb** [comment]
Looks fine over here.

**Pull request merged**
