### PR TITLE
5.15-23.08 runtime

### PR DESCRIPTION
**Pull request by hfiguiere**
Branch will need to be created manually.

### CODE REVIEW

**Comment by JakobDev** [comment]
Thanks. I have now created the new branch and stopped the build of the new branch on the buildserver. Can you retarget the PR?

**Comment by hfiguiere** [comment]
you could just have pushed my branch directly.... (or I could have just done it)

that would have avoided to have a "broken branch".

**Comment by JakobDev** [comment]
Is it possible, to merge a PR into a new branch?

**Comment by JakobDev** [comment]
bot, build

**Comment by JakobDev** [comment]
Looks like it's working. Thanks.

**Comment by hfiguiere** [comment]
> Is it possible, to merge a PR into a new branch?

`git push`.

Github is useless here.

**Pull request merged**
