### PR TITLE
Add 6.3 branch

### PR DESCRIPTION
**Pull request by tinywrkb**
It seems like KDE 6.3 is almost here. Previously, I built QtWebEngine 6.3 with KDE 6.2, so updating QtWebEngine.BaseApp shouldn't be difficult, I already have a PR lined-up.  
This one here serves to test building on the CI, as I would like to avoid cross-compiling locally for aarch64.

### CODE REVIEW

**Comment by tinywrkb** [comment]
Oh! And I think that we might still have Desktop OpenGL on aarch64.

**Comment by JakobDev** [comment]
I just wanna ask, what the current state of this is. I don't think this will break anything. I'm [currently the only person who uses 6.2](https://jakobdev.github.io/flathub-data-viewer/?type=BaseApp&first=com.riverbankcomputing.PyQt.BaseApp&second=6.2) and my Apps are all working with Qt 6.3.

**Comment by tinywrkb** [comment]
This will be merged into a new `branch/6.3` branch after https://github.com/flathub/io.qt.qtwebengine.BaseApp/pull/69.
If there won't be apps in stable that are using 6.2, then maybe set it as EOL.

Note that I actually have a minor change locally that is not included in this PR.

**Comment by tinywrkb** [comment]
Added in a new branch/6.3.

**Comment by JakobDev** [comment]
I have updated all my Apps to 6.3 so there is no one using 6.2 anymore. You can make 6.2 EOL.

**Comment by tinywrkb** [comment]
@JakobDev thanks, I created #51 and #52.

**Pull request closed without merging**
